[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"
  # You can keep your EXPO_PUBLIC_NASA_API_KEY in Netlify UI (recommended).
  # If you prefer to set it here instead, uncomment the next line and paste your key:
  # EXPO_PUBLIC_NASA_API_KEY = "YOUR_KEY_HERE"

# ---- Security headers (CSP) ----
[[headers]]
  for = "/*"
  [headers.values]
    # Allow your app to fetch from NASA + your existing services
    Content-Security-Policy = """
      default-src 'self';
      connect-src 'self' https://api.stripe.com https://*.supabase.co https://translation.googleapis.com https://api.nasa.gov;
      img-src 'self' data: blob: https://apod.nasa.gov https://img.youtube.com https://i.ytimg.com;
      media-src 'self' https://apod.nasa.gov https://www.youtube.com https://youtube.com;
      frame-src 'self' https://www.youtube.com https://youtube.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      font-src 'self' data:;
    """
